<?php

namespace Fake\Kernels\Http\Controllers;

use Neutrino\Http\Controller;

/**
 * Class StubController
 *
 * @package     Stub
 */
class StubController extends Controller
{
    /**
     * @var array
     */
    public static $middlewares = [];

    /**
     * @var array
     */
    public static $registerMiddlewares = [];

    /**
     * Event called on controller construction
     *
     * Register middleware here.
     */
    protected function onConstruct()
    {
        parent::onConstruct();

        foreach (self::$middlewares as $middleware) {
            foreach ($middleware['params'] as $key => $method) {
                $this->middleware($middleware['middleware'],...(isset($middleware['construct']) ? $middleware['construct'] : []))->$key($method);
            }
        }
    }

    protected function middleware($middlewareClass, ...$params)
    {
        return self::$registerMiddlewares[] = parent::middleware($middlewareClass, ...$params); // TODO: Change the autogenerated stub
    }

    public function indexAction(): void
    {
    }

    public function returnAction(): string
    {
        return __METHOD__;
    }

    public function dataAction(): string
    {
        $request = $this->request;

        return json_encode([
            'method'  => $request->getMethod(),
            'get'     => $_GET,
            'post'    => $_POST,
            'headers' => array_filter(['X-Test' => $request->getHeader('X-Test'), 'Content-Type' => $request->getContentType()]),
            'json'    => $request->getJsonRawBody(true),
        ], JSON_THROW_ON_ERROR);
    }

    public function redirectAction(): void
    {
        $this->response->redirect('/');
    }

    public function forwardedAction(): bool
    {
        $this->dispatcher->forward([
            "controller" => "Stub",
            "action" => "index",
        ]);

        return false;
    }
}
