<?php

declare(strict_types=1);

namespace Neutrino\Support\IdeHelper;

use Closure;
use Neutrino\Support\AtomicFile;
use Neutrino\Support\Facades;
use Neutrino\Support\Provider;
use Phalcon\Di\DiInterface;
use Phalcon\Di\ServiceInterface;
use ReflectionClass;
use ReflectionFunction;
use ReflectionMethod;
use ReflectionNamedType;
use Throwable;

/**
 * Documents the container of a booted application for IDEs and static analysis.
 *
 * - `_ide_helper.php`: the `@method static` of each Facade, and a `@property-read` per service
 *   on `Phalcon\Di\Injectable` (`$this->router` in controllers, tasks, listeners…).
 *   Usable by PHPStan through `stubFiles`.
 * - `.phpstorm.meta.php`: the class returned by `DiInterface::get()` and `getShared()` for each service.
 *
 * The class of a service is found without building it whenever possible:
 * 1. a class name definition (`'name' => Class::class`, a `SimpleProvider`, the `FactoryDefault` services);
 * 2. the return type of `Provider::register()`;
 * 3. the return type of a closure definition;
 * 4. otherwise, by resolving the service (errors are ignored and the service is left out).
 */
final class Generator
{
    public const string IDE_HELPER_FILE = '_ide_helper.php';

    public const string PHPSTORM_META_FILE = '.phpstorm.meta.php';

    /**
     * The Facades of the framework.
     */
    public const array FACADES = [
        Facades\Auth::class,
        Facades\Cache::class,
        Facades\Flash::class,
        Facades\Log::class,
        Facades\Micro\Router::class,
        Facades\Request::class,
        Facades\Response::class,
        Facades\Router::class,
        Facades\Session::class,
        Facades\Url::class,
        Facades\View::class,
    ];

    /** @var array<string, class-string>|null */
    private ?array $services = null;

    /**
     * @param list<class-string<Facades\Facade>> $facades Facades to document: the framework's and the application's
     */
    public function __construct(
        private readonly DiInterface $di,
        private readonly array $facades = self::FACADES,
    ) {}

    /**
     * Class of each service, by service name. Services whose class cannot be found are left out.
     *
     * @return array<string, class-string>
     */
    public function services(): array
    {
        if ($this->services !== null) {
            return $this->services;
        }

        $services = [];

        foreach ($this->di->getServices() as $name => $service) {
            $class = $this->classOf((string) $name, $service);

            if ($class !== null) {
                $services[(string) $name] = $class;
            }
        }

        ksort($services);

        return $this->services = $services;
    }

    /**
     * Writes `_ide_helper.php` and `.phpstorm.meta.php` in `$directory`.
     *
     * @return list<string> The files written
     */
    public function write(string $directory): array
    {
        $files = [
            $directory . DIRECTORY_SEPARATOR . self::IDE_HELPER_FILE => $this->renderIdeHelper(),
            $directory . DIRECTORY_SEPARATOR . self::PHPSTORM_META_FILE => $this->renderPhpStormMeta(),
        ];

        foreach ($files as $file => $content) {
            AtomicFile::write($file, $content);
        }

        return array_keys($files);
    }

    public function renderIdeHelper(): string
    {
        $services = $this->services();

        $namespaces = [];

        foreach ($this->facades as $facade) {
            $service = $this->facadeService($facade, $services);
            if ($service === null) {
                continue;
            }

            $reflection = new ReflectionClass($facade);
            $lines = ['@see \\' . $service, '', '@method static \\' . $service . ' getFacadeRoot()'];

            foreach ((new ReflectionClass($service))->getMethods(ReflectionMethod::IS_PUBLIC) as $method) {
                if (!str_starts_with($method->getName(), '__')) {
                    $lines[] = '@method static ' . SignatureRenderer::method($method, $service);
                }
            }

            $namespaces[$reflection->getNamespaceName()][] = self::docBlock($lines, '    ')
                . '    class ' . $reflection->getShortName() . ' extends \\' . Facades\Facade::class . "\n    {\n    }\n";
        }

        $properties = [];
        foreach ($services as $name => $class) {
            if (preg_match('/^[A-Za-z_]\w*$/', $name) === 1) {
                $properties[] = '@property-read \\' . $class . ' $' . $name;
            }
        }

        $namespaces['Phalcon\\Di'][] = self::docBlock($properties, '    ') . "    abstract class Injectable\n    {\n    }\n";

        $content = "<?php\n\n"
            . "// Generated by \\" . self::class . ". Do not edit, do not include:\n"
            . "// this file documents the application for IDEs and static analysis only.\n\n"
            . "// @formatter:off\n";

        foreach ($namespaces as $namespace => $classes) {
            $content .= "\nnamespace $namespace {\n" . implode("\n", $classes) . "}\n";
        }

        return $content;
    }

    public function renderPhpStormMeta(): string
    {
        $map = '';
        foreach ($this->services() as $name => $class) {
            $map .= '            ' . var_export($name, true) . ' => \\' . $class . "::class,\n";
        }

        $content = "<?php\n\n"
            . "// Generated by \\" . self::class . ". Do not edit.\n\n"
            . "namespace PHPSTORM_META {\n";

        foreach (['\\Phalcon\\Di\\DiInterface::get(0)', '\\Phalcon\\Di\\DiInterface::getShared(0)', '\\Phalcon\\Di\\Di::get(0)', '\\Phalcon\\Di\\Di::getShared(0)'] as $method) {
            $content .= "    override($method, map([\n$map    ]));\n";
        }

        return $content . "}\n";
    }

    /**
     * @return class-string|null
     */
    private function classOf(string $name, ServiceInterface $service): ?string
    {
        $definition = $service->getDefinition();

        $class = match (true) {
            is_string($definition) => $definition,
            is_array($definition) && is_string($definition['className'] ?? null) => $definition['className'],
            $definition instanceof Closure => $this->closureClass($definition),
            is_object($definition) => $definition::class,
            default => null,
        };

        if ($class !== null && self::classExists($class)) {
            return $class;
        }

        try {
            $instance = $this->di->get($name);
        } catch (Throwable) {
            return null;
        }

        return is_object($instance) ? $instance::class : null;
    }

    /**
     * Return type of the closure, or of `register()` for a closure created by a {@see Provider}.
     */
    private function closureClass(Closure $closure): ?string
    {
        $function = new ReflectionFunction($closure);

        $provider = $function->getClosureUsedVariables()['self'] ?? null;
        $type = $provider instanceof Provider
            ? (new ReflectionMethod($provider, 'register'))->getReturnType()
            : $function->getReturnType();

        return $type instanceof ReflectionNamedType && !$type->isBuiltin() ? $type->getName() : null;
    }

    /**
     * @param class-string<Facades\Facade> $facade
     * @param array<string, class-string>  $services
     *
     * @return class-string|null
     */
    private function facadeService(string $facade, array $services): ?string
    {
        try {
            $accessor = (new ReflectionMethod($facade, 'getFacadeAccessor'))->invoke(null);
        } catch (Throwable) {
            return null;
        }

        if (is_object($accessor)) {
            return $accessor::class;
        }

        return is_string($accessor) ? $services[$accessor] ?? null : null;
    }

    /**
     * Loading a class can fail (e.g. it implements an interface that does not exist).
     *
     * @phpstan-assert-if-true class-string $class
     */
    private static function classExists(string $class): bool
    {
        try {
            return class_exists($class) || interface_exists($class);
        } catch (Throwable) {
            return false;
        }
    }

    /**
     * @param list<string> $lines
     */
    private static function docBlock(array $lines, string $indent): string
    {
        $block = "$indent/**\n";
        foreach ($lines as $line) {
            $block .= rtrim("$indent * $line") . "\n";
        }

        return $block . "$indent */\n";
    }
}
