<?php

namespace Neutrino\Foundation\Cli\Tasks;

use Neutrino\Cli\Task;

/**
 * Class ClearCompiledTask
 *
 * @package Neutrino\Foundation\Cli
 */
class ClearCompiledTask extends Task
{
    /**
     * @description Clear compilation.
     */
    public function mainAction()
    {
        self::clearLoader(BASE_PATH . DIRECTORY_SEPARATOR . 'bootstrap/compile/');

        $this->info('The compiled files have been removed.');
    }

    /**
     * Handle the post-[install|update] Composer event.
     *
     * @return void
     */
    public static function composerClearCompiled()
    {
        self::clearLoader(getcwd() . DIRECTORY_SEPARATOR . 'bootstrap/compile/');
    }

    /**
     * Deleting Compiled Files
     *
     * @param string $compileDir
     */
    private static function clearLoader($compileDir)
    {
        // loader.php and compile.php were generated by the 1.x optimizer.
        foreach (['loader.php', 'compile.php', 'preload.php'] as $file) {
            if (file_exists($compileDir . $file)) {
                @unlink($compileDir . $file);
            }
        }
    }
}
