<?php

declare(strict_types=1);

namespace Neutrino\Foundation\Cli\Tasks;

use Neutrino\Cli\Attribute\Description;
use Neutrino\Cli\Task;

final class ClearCompiledTask extends Task
{
    #[Description('Remove the compiled class files.')]
    public function mainAction(): void
    {
        self::clearLoader(BASE_PATH . '/bootstrap/compile/');

        $this->info('The compiled files have been removed.');
    }

    /**
     * Composer script (`post-autoload-dump`): runs from the application directory.
     */
    public static function composerClearCompiled(): void
    {
        self::clearLoader(getcwd() . '/bootstrap/compile/');
    }

    private static function clearLoader(string $compileDir): void
    {
        // loader.php and compile.php were generated by the 1.x optimizer.
        foreach (['loader.php', 'compile.php', 'preload.php'] as $file) {
            if (is_file($compileDir . $file)) {
                @unlink($compileDir . $file);
            }
        }
    }
}
